name: Lighthouse gather data 100-200 CI
on: [push, pull_request]
env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install NPM dependencies
      run: npm ci

    - name: Lighthouse
      run: npm run rollup && npm run build

    - uses: stefanzweifel/git-auto-commit-action@v4.11.0
      with:
        commit_message: Adding automatic Image/Lighthouse data collection changes...
        branch: ${{ github.head_ref }}
